// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSOPkt9InUTsEXeuVrNxM2t8Wt4daOtJQ',
    appId: '1:272211341877:web:2a04cff22d65caead0f77c',
    messagingSenderId: '272211341877',
    projectId: 'bikynav',
    authDomain: 'bikynav.firebaseapp.com',
    storageBucket: 'bikynav.firebasestorage.app',
    measurementId: 'G-QCSPPRJXVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLSXURj7m7J69vVvMq37Rhe_7fixFnXQ8',
    appId: '1:272211341877:android:17c02b1b4796f483d0f77c',
    messagingSenderId: '272211341877',
    projectId: 'bikynav',
    storageBucket: 'bikynav.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl1iKvD5hfUwS3cEMep2Hq29KPLR5gR3s',
    appId: '1:272211341877:ios:38d10cec9c21cfd8d0f77c',
    messagingSenderId: '272211341877',
    projectId: 'bikynav',
    storageBucket: 'bikynav.firebasestorage.app',
    iosBundleId: 'com.example.bikynav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl1iKvD5hfUwS3cEMep2Hq29KPLR5gR3s',
    appId: '1:272211341877:ios:38d10cec9c21cfd8d0f77c',
    messagingSenderId: '272211341877',
    projectId: 'bikynav',
    storageBucket: 'bikynav.firebasestorage.app',
    iosBundleId: 'com.example.bikynav',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSOPkt9InUTsEXeuVrNxM2t8Wt4daOtJQ',
    appId: '1:272211341877:web:21e51eb7b91cd273d0f77c',
    messagingSenderId: '272211341877',
    projectId: 'bikynav',
    authDomain: 'bikynav.firebaseapp.com',
    storageBucket: 'bikynav.firebasestorage.app',
    measurementId: 'G-3TZV8LFELJ',
  );

}